image: mcr.microsoft.com/dotnet/sdk:6.0.101-bullseye-slim

# ### Define variables
#
variables:
  # Name of pnpm cache directory
  PNPM_CACHE: ".pnpm-store"
  # NodeJS version
  NODE_VERSION: "16"
  # Name of directory where restore and build objects are stored.
  OBJECTS_DIRECTORY: "obj"
  # Name of directory used for keeping restored dependencies.
  NUGET_PACKAGES_DIRECTORY: ".nuget"
  # A relative path to the source code from project repository root.
  # NOTE: Please edit this path so it matches the structure of your project!
  SOURCE_CODE_PATH: "apps"
  PACKAGES_CODE_PATH: "packages"
  CORE: "core"
  UI: "ui"
  IDENTITY_SERVICE: "IdentityService"
  IDENTITY_SERVICE_ADMIN: "IdentityService.Admin"
  IDENTITY_SERVICE_UNIT_TEST: "IdentityService.UnitTest"

before_script:
  - curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x |  bash -
  - apt-get install -y nodejs
  - node --version
  - npm install --global pnpm
  - pnpm --version
  - pnpm config set store-dir $PNPM_CACHE
  - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY
  - pnpm install

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $PNPM_CACHE
    - node_modules/
    - "$SOURCE_CODE_PATH/$IDENTITY_SERVICE/ClientApp/node_modules/"
    - "$SOURCE_CODE_PATH/$IDENTITY_SERVICE_ADMIN/ClientApp/node_modules/"
    - "$PACKAGES_CODE_PATH/$CORE/node_modules/"
    - "$PACKAGES_CODE_PATH/$UI/node_modules/"
    # Main JSON file holding information about package dependency tree, packages versions,
    # frameworks etc. It also holds information where to the dependencies were restored.
    - "$SOURCE_CODE_PATH/$IDENTITY_SERVICE/obj/project.assets.json"
    - "$SOURCE_CODE_PATH/$IDENTITY_SERVICE_ADMIN/obj/project.assets.json"
    - "$SOURCE_CODE_PATH/$IDENTITY_SERVICE_UNIT_TEST/obj/project.assets.json"
    # Other NuGet and MSBuild related files. Also needed.
    - "$SOURCE_CODE_PATH/$IDENTITY_SERVICE/obj/*.csproj.nuget.*"
    - "$SOURCE_CODE_PATH/$IDENTITY_SERVICE_ADMIN/obj/*.csproj.nuget.*"
    - "$SOURCE_CODE_PATH/$IDENTITY_SERVICE_UNIT_TEST/obj/*.csproj.nuget.*"
    - $NUGET_PACKAGES_DIRECTORY

stages:
  - build
  - build-storybook
  - lint
  - test

build:
  stage: build
  script:
    - pnpm build
    - dotnet build --no-restore

build-storybook:
  stage: build-storybook
  script:
    - pnpm build-storybook

lint:
  stage: lint
  script:
    - pnpm lint
    - dotnet tool restore
    - dotnet format

test:
  stage: test
  script:
    - npm i -g yarn
    - dotnet tool restore
    - dotnet cake test.cake
