name: JIRA

on:
  push:
    branches: [ develop ]

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find Issue Key
        id: find
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ github.head_ref }}

      - name: Find issue info
        run: echo "Issue ${{ steps.find.outputs.issue }} was found"

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.find.outputs.issue }}
          transition: "Done"
